blank_issues_enabled: false

contact_links:
  - name: Game Master proposals
    url: https://github.com/godotengine/godot-proposals
    about: Please submit feature proposals on the Game Master proposals repository, not here.

  - name: Game Master documentation repository
    url: https://github.com/godotengine/godot-docs
    about: Please report issues with documentation on the Game Master documentation repository, not here.

  - name: Game Master community channels
    url: https://godotengine.org/community
    about: Please ask for technical support on one of the other community channels, not here.
